export const API = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    oauth: (provider: string) => `/auth/oauth/${provider}`,
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  users: {
    me: '/users/me',
    profile: '/users/me/profile',
    settings: '/users/me/settings',
    deleteAccount: '/users/me',
  },
  resumes: {
    list: '/resumes',
    detail: (id: string) => `/resumes/${id}`,
    sections: (id: string) => `/resumes/${id}/sections`,
    score: (id: string) => `/resumes/${id}/score`,
    tailor: (id: string) => `/resumes/${id}/tailor`,
    export: (id: string, format: string) => `/resumes/${id}/export?format=${format}`,
    upload: '/resumes/upload',
    parse: '/resumes/parse',
  },
  coverLetters: {
    list: '/cover-letters',
    detail: (id: string) => `/cover-letters/${id}`,
    generate: '/cover-letters/generate',
    export: (id: string) => `/cover-letters/${id}/export`,
  },
  jobs: {
    search: '/jobs',
    detail: (id: string) => `/jobs/${id}`,
    matches: '/jobs/matches',
    matchDetail: (id: string) => `/jobs/matches/${id}`,
    recommendations: '/jobs/recommendations',
    save: (id: string) => `/jobs/${id}/save`,
    saved: '/jobs/saved',
    semanticSearch: '/jobs/semantic-search',
    facets: '/jobs/facets',
    aggregate: '/jobs/aggregate',
  },
  applications: {
    list: '/applications',
    create: '/applications',
    detail: (id: string) => `/applications/${id}`,
    status: (id: string) => `/applications/${id}/status`,
    notes: (id: string) => `/applications/${id}/notes`,
    attachments: (id: string) => `/applications/${id}/attachments`,
    followUps: (id: string) => `/applications/${id}/follow-ups`,
    automate: (id: string) => `/applications/${id}/automate`,
    timeline: (id: string) => `/applications/${id}/timeline`,
  },
  interviews: {
    sessions: '/interviews/sessions',
    sessionDetail: (id: string) => `/interviews/sessions/${id}`,
    nextQuestion: (id: string) => `/interviews/sessions/${id}/next-question`,
    answer: (id: string, qid: string) => `/interviews/sessions/${id}/questions/${qid}/answer`,
    complete: (id: string) => `/interviews/sessions/${id}/complete`,
    questionBank: '/interviews/questions',
  },
  companies: {
    search: '/companies/search',
    detail: (id: string) => `/companies/${id}`,
    techStack: (id: string) => `/companies/${id}/tech-stack`,
    salary: (id: string) => `/companies/${id}/salary`,
    interviews: (id: string) => `/companies/${id}/interviews`,
    hiringTrends: (id: string) => `/companies/${id}/hiring-trends`,
  },
  analytics: {
    overview: '/analytics/overview',
    applicationFunnel: '/analytics/application-funnel',
    skillGaps: '/analytics/skill-gaps',
    resumeTrend: '/analytics/resume-trend',
    marketBenchmarks: '/analytics/market-benchmarks',
    interviewPerformance: '/analytics/interview-performance',
    timeline: '/analytics/timeline',
    activity: '/analytics/activity',
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
    preferences: '/notifications/preferences',
  },
  admin: {
    users: '/admin/users',
    userDetail: (id: string) => `/admin/users/${id}`,
    suspend: (id: string) => `/admin/users/${id}/suspend`,
    unsuspend: (id: string) => `/admin/users/${id}/unsuspend`,
    auditLog: '/admin/audit-log',
    metrics: '/admin/metrics/summary',
    featureFlags: '/admin/feature-flags',
    featureFlagToggle: (key: string) => `/admin/feature-flags/${key}`,
  },
  ai: {
    generate: '/ai/generate',
    generateStream: '/ai/generate/stream',
    embeddings: '/ai/embeddings',
    health: '/ai/health',
  },
  agent: {
    chat: '/api/v1/agent/chat',
    status: '/api/v1/agent/status',
    missions: '/api/v1/agent/missions',
    userMissions: '/api/v1/agent/missions/user/current',
    startMission: (id: string) => `/api/v1/agent/missions/${id}/start`,
    pauseMission: (id: string) => `/api/v1/agent/missions/${id}/pause`,
    cancelMission: (id: string) => `/api/v1/agent/missions/${id}/cancel`,
    automateStatus: '/api/v1/agent/automate/status',
    automateStart: '/api/v1/agent/automate/start',
    automateStop: '/api/v1/agent/automate/stop',
    automateResults: '/api/v1/agent/automate/results',
    automateBoards: '/api/v1/agent/automate/boards',
    captchaSolve: '/api/v1/agent/automate/captcha/solve',
    emailEvents: '/api/v1/agent/email/events',
    emailEventCounts: '/api/v1/agent/email/events/counts',
    emailProcess: '/api/v1/agent/email/process',
  },
  search: {
    query: '/search',
    suggestions: '/search/suggestions',
  },
  settings: {
    all: '/settings',
    profile: '/settings/profile',
    jobPreferences: '/settings/job-preferences',
    privacy: '/settings/privacy',
    ai: '/settings/ai',
    billing: '/settings/billing',
    invoices: '/settings/billing/invoices',
    cancelSubscription: '/settings/billing/cancel',
    apiKeys: '/settings/api-keys',
    apiKeyDetail: (id: string) => `/settings/api-keys/${id}`,
  },
} as const;
