global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'jobpilot-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'jobpilot-api'
          environment: 'dev'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']

  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9308']
