package com.jobpilot.domain.agent;

public enum MemoryType {
    PREFERENCE,
    REJECTED_COMPANY,
    APPLIED_COMPANY,
    BLOCKED_COMPANY,
    SALARY_PREFERENCE,
    LOCATION_PREFERENCE,
    SKILL_PREFERENCE,
    INTERVIEW_HISTORY,
    RESUME_VERSION,
    SUCCESS_RATE,
    LEARNED_BEHAVIOR,
    USER_INSTRUCTION,
    OBSERVATION,
    DECISION
}
