package com.jobpilot.domain.agent;

public enum ObservationType {
    JOB_FOUND,
    JOB_MATCHED,
    JOB_REJECTED,
    APPLICATION_SUBMITTED,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    APPLICATION_ERROR,
    RESUME_TAILORED,
    COVER_LETTER_GENERATED,
    SCREENSHOT_TAKEN,
    USER_FEEDBACK,
    SYSTEM_EVENT,
    ERROR_OCCURRED,
    MISSION_PROGRESS,
    DEADLINE_WARNING,
    DAILY_LIMIT_REACHED
}
